# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weatherGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_weatherGUI(object):
    def setupUi(self, weatherGUI):
        weatherGUI.setObjectName("weatherGUI")
        weatherGUI.resize(1026, 708)
        self.pushButton1 = QtWidgets.QPushButton(weatherGUI)
        self.pushButton1.setGeometry(QtCore.QRect(470, 250, 112, 34))
        self.pushButton1.setObjectName("pushButton1")
        self.label_2 = QtWidgets.QLabel(weatherGUI)
        self.label_2.setGeometry(QtCore.QRect(400, 180, 36, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(weatherGUI)
        self.label_3.setGeometry(QtCore.QRect(660, 180, 36, 18))
        self.label_3.setObjectName("label_3")
        self.line3 = QtWidgets.QLineEdit(weatherGUI)
        self.line3.setGeometry(QtCore.QRect(710, 170, 151, 51))
        self.line3.setObjectName("line3")
        self.label_4 = QtWidgets.QLabel(weatherGUI)
        self.label_4.setGeometry(QtCore.QRect(130, 180, 41, 18))
        self.label_4.setObjectName("label_4")
        self.line1 = QtWidgets.QLineEdit(weatherGUI)
        self.line1.setGeometry(QtCore.QRect(180, 170, 131, 51))
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QLineEdit(weatherGUI)
        self.line2.setGeometry(QtCore.QRect(450, 170, 141, 51))
        self.line2.setObjectName("line2")
        self.textBrowser11 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser11.setGeometry(QtCore.QRect(120, 360, 241, 31))
        self.textBrowser11.setObjectName("textBrowser11")
        self.textBrowser12 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser12.setGeometry(QtCore.QRect(390, 360, 111, 31))
        self.textBrowser12.setObjectName("textBrowser12")
        self.textBrowser13 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser13.setGeometry(QtCore.QRect(530, 360, 231, 31))
        self.textBrowser13.setObjectName("textBrowser13")
        self.textBrowser14 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser14.setGeometry(QtCore.QRect(840, 360, 111, 31))
        self.textBrowser14.setObjectName("textBrowser14")
        self.textBrowser23 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser23.setGeometry(QtCore.QRect(530, 410, 231, 31))
        self.textBrowser23.setObjectName("textBrowser23")
        self.textBrowser22 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser22.setGeometry(QtCore.QRect(390, 410, 111, 31))
        self.textBrowser22.setObjectName("textBrowser22")
        self.textBrowser24 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser24.setGeometry(QtCore.QRect(840, 410, 111, 31))
        self.textBrowser24.setObjectName("textBrowser24")
        self.textBrowser21 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser21.setGeometry(QtCore.QRect(120, 410, 241, 31))
        self.textBrowser21.setObjectName("textBrowser21")
        self.textBrowser33 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser33.setGeometry(QtCore.QRect(530, 460, 231, 31))
        self.textBrowser33.setObjectName("textBrowser33")
        self.textBrowser32 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser32.setGeometry(QtCore.QRect(390, 460, 111, 31))
        self.textBrowser32.setObjectName("textBrowser32")
        self.textBrowser34 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser34.setGeometry(QtCore.QRect(840, 460, 111, 31))
        self.textBrowser34.setObjectName("textBrowser34")
        self.textBrowser31 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser31.setGeometry(QtCore.QRect(120, 460, 241, 31))
        self.textBrowser31.setObjectName("textBrowser31")
        self.textBrowser43 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser43.setGeometry(QtCore.QRect(530, 510, 231, 31))
        self.textBrowser43.setObjectName("textBrowser43")
        self.textBrowser42 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser42.setGeometry(QtCore.QRect(390, 510, 111, 31))
        self.textBrowser42.setObjectName("textBrowser42")
        self.textBrowser44 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser44.setGeometry(QtCore.QRect(840, 510, 111, 31))
        self.textBrowser44.setObjectName("textBrowser44")
        self.textBrowser41 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser41.setGeometry(QtCore.QRect(120, 510, 241, 31))
        self.textBrowser41.setObjectName("textBrowser41")
        self.textBrowser53 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser53.setGeometry(QtCore.QRect(530, 560, 231, 31))
        self.textBrowser53.setObjectName("textBrowser53")
        self.textBrowser52 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser52.setGeometry(QtCore.QRect(390, 560, 111, 31))
        self.textBrowser52.setObjectName("textBrowser52")
        self.textBrowser54 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser54.setGeometry(QtCore.QRect(840, 560, 111, 31))
        self.textBrowser54.setObjectName("textBrowser54")
        self.textBrowser51 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser51.setGeometry(QtCore.QRect(120, 560, 241, 31))
        self.textBrowser51.setObjectName("textBrowser51")
        self.textBrowser63 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser63.setGeometry(QtCore.QRect(530, 600, 231, 31))
        self.textBrowser63.setObjectName("textBrowser63")
        self.textBrowser62 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser62.setGeometry(QtCore.QRect(390, 600, 111, 31))
        self.textBrowser62.setObjectName("textBrowser62")
        self.textBrowser64 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser64.setGeometry(QtCore.QRect(840, 600, 111, 31))
        self.textBrowser64.setObjectName("textBrowser64")
        self.textBrowser61 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser61.setGeometry(QtCore.QRect(120, 600, 241, 31))
        self.textBrowser61.setObjectName("textBrowser61")
        self.textBrowser74 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser74.setGeometry(QtCore.QRect(840, 650, 111, 31))
        self.textBrowser74.setObjectName("textBrowser74")
        self.textBrowser73 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser73.setGeometry(QtCore.QRect(530, 650, 231, 31))
        self.textBrowser73.setObjectName("textBrowser73")
        self.textBrowser72 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser72.setGeometry(QtCore.QRect(390, 650, 111, 31))
        self.textBrowser72.setObjectName("textBrowser72")
        self.textBrowser71 = QtWidgets.QTextBrowser(weatherGUI)
        self.textBrowser71.setGeometry(QtCore.QRect(120, 650, 241, 31))
        self.textBrowser71.setObjectName("textBrowser71")
        self.label_5 = QtWidgets.QLabel(weatherGUI)
        self.label_5.setGeometry(QtCore.QRect(350, 50, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(weatherGUI)
        self.label_6.setGeometry(QtCore.QRect(230, 330, 81, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(weatherGUI)
        self.label_7.setGeometry(QtCore.QRect(420, 330, 81, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(weatherGUI)
        self.label_8.setGeometry(QtCore.QRect(630, 330, 81, 18))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(weatherGUI)
        self.label_9.setGeometry(QtCore.QRect(880, 330, 81, 18))
        self.label_9.setObjectName("label_9")
        self.lcdNumber1 = QtWidgets.QLCDNumber(weatherGUI)
        self.lcdNumber1.setGeometry(QtCore.QRect(730, 110, 71, 31))
        self.lcdNumber1.setObjectName("lcdNumber1")
        self.lcdNumber2 = QtWidgets.QLCDNumber(weatherGUI)
        self.lcdNumber2.setGeometry(QtCore.QRect(810, 110, 71, 31))
        self.lcdNumber2.setObjectName("lcdNumber2")
        self.lcdNumber3 = QtWidgets.QLCDNumber(weatherGUI)
        self.lcdNumber3.setGeometry(QtCore.QRect(890, 110, 71, 31))
        self.lcdNumber3.setObjectName("lcdNumber3")

        self.retranslateUi(weatherGUI)
        QtCore.QMetaObject.connectSlotsByName(weatherGUI)

    def retranslateUi(self, weatherGUI):
        _translate = QtCore.QCoreApplication.translate
        weatherGUI.setWindowTitle(_translate("weatherGUI", "Form"))
        self.pushButton1.setText(_translate("weatherGUI", "查询"))
        self.label_2.setText(_translate("weatherGUI", "城市"))
        self.label_3.setText(_translate("weatherGUI", "县区"))
        self.line3.setText(_translate("weatherGUI", "昆山"))
        self.label_4.setText(_translate("weatherGUI", "省份"))
        self.line1.setText(_translate("weatherGUI", "江苏"))
        self.line2.setText(_translate("weatherGUI", "苏州"))
        self.label_5.setText(_translate("weatherGUI", "咖喱怪天气预报"))
        self.label_6.setText(_translate("weatherGUI", "日期"))
        self.label_7.setText(_translate("weatherGUI", "天气"))
        self.label_8.setText(_translate("weatherGUI", "风力"))
        self.label_9.setText(_translate("weatherGUI", "温度"))

